# Site settings
title: Farmapronto Villa de Alvarez
email: vdealvarez@grupofarmapronto.com
description: > # this means to ignore newlines until "baseurl:"
  Av. Maria Ahumada De Gomez No. 478 Local 5 y 6, Villa De Alvarez, Colima 
  (312) 396-9020
baseurl: "/farmaprontovilladealvarez" # the subpath of your site, e.g. /blog/
url: "http://farmaprontovilladealvarez.mx" # the base hostname & protocol for your site
twitter_username: farmapronto.villadealvarez
facebook_username: farmapronto.villadealvarez
github_username:  elzr
   
# Build settings
markdown: kramdown
